name: CI

on:
  push:

jobs:
  unittest:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Force Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: run oneHookLibraryUnitTests
        run: xcodebuild test -scheme oneHookLibraryUnitTests -project oneHookLibrarySwift.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12'
